### ISSUE TITLE
我能提供校园网的账号和密码，大佬能帮忙做个我们学校的吗

### ISSUE THREAD

**Issue by asd43a** [lcandy2/webvpn-converter#156]
我们学校给的vpn不知道怎么回事访问不了校园网，想查资料也没办法，向学校反应他们说只给校内用学校的知网账号。
我不知道学校的那个webvpn地址，但可以提供学校的vpn文章链接和vpn运行的日志，不知道能否从中间解析出地址

**Comment by lcandy2** [comment]
close for now
