### ISSUE TITLE
[Feature Request] bookmarklet版本

### ISSUE THREAD

**Issue by feeshy** [lcandy2/webvpn-converter#18]
如果能直接点击小书签转换，应该会比打开网页粘贴更加方便，开发大大有兴趣搞一个吗？

**Comment by lcandy2** [comment]
好 等过阵有时间就搞

**Comment by lcandy2** [comment]
bookmarklet功能已在新版可用，欢迎体验！

![CleanShot 2024-03-29 at 21 28 09@2x](https://github.com/lcandy2/webvpn-converter/assets/45784494/444fa76e-f1ed-424c-9b87-bfdb5f7e2d46)

新版：[https://webvpn-converter-git-next-lcandy.vercel.app/bookmarklet](https://webvpn-converter-git-next-lcandy.vercel.app/bookmarklet)
