### ISSUE TITLE
部分高校已经失效，似乎更换了加密密钥

### ISSUE THREAD

**Issue by LordHumphrey** [lcandy2/webvpn-converter#23]
部分高校已经失效，似乎更换了加密密钥

**Comment by lcandy2** [comment]
可以自定义加密密钥 或者提pr修改

**Comment by LordHumphrey** [comment]
事实上，据可靠消息，已经发通知普遍整改默认密钥了

**Comment by lcandy2** [comment]
这个我不太了解，有的可以直接在前端网页源代码中看到iv和key，anyway程序并没有写死，可以直接在网页中修改，也可以提交pr更新数据库
