### ISSUE TITLE
请教如何分析学校的地址转换加密，我想做个中国地质大学北京的

### ISSUE THREAD

**Issue by lcg29** [lcandy2/webvpn-converter#25]
目前我有一些已知学校设置的的webvpn网站地址及其对应的源地址。但是有的网站学校没设置链接地址。我想自己搞一个

**Comment by lcandy2** [comment]
中国地质大学北京用的是深信服webvpn，这个转换工具不支持的，可以发邮件给我私聊联系

**Comment by lcg29** [comment]
Hi lcandy2,
需要我配合做一下吗？
怎么搞
| |


|
|
***@***.***
祝您身体健康，工作顺利！
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月8日 17:13 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [lcandy2/webvpn-converter] 请教如何分析学校的地址转换加密，我想做个中国地质大学北京的 (Issue #25) |

中国地质大学北京用的是深信服webvpn，这个转换工具不支持的，可以发邮件给我私聊联系
