### ISSUE TITLE
或许可以做成浏览器插件

### ISSUE THREAD

**Issue by Cloudac7** [lcandy2/webvpn-converter#43]
其实比较常用的工作流是先把文献找到然后再转换到WebVPN，因此比较方便的做法是做一个按钮跳转或者右键跳转。
这样从使用的角度比较方便，而且只会对在真正需要代理的网站精确使用，不会对校园网代理服务产生额外负担。

之前参考其他学校的实现以及原项目做了一个版本，但是没有支持非默认Key，只是给了一个选项用于修改默认VPN链接，大佬如果有心思可以考虑在此基础上改进
https://github.com/Cloudac7/webvpn-converter

**Comment by lcandy2** [comment]
正在开发中，感谢建议

**Comment by lcandy2** [comment]
bookmarklet功能已在新版可用，欢迎体验！

![CleanShot 2024-03-29 at 21 28 09@2x](https://github.com/lcandy2/webvpn-converter/assets/45784494/444fa76e-f1ed-424c-9b87-bfdb5f7e2d46)

新版：[https://webvpn-converter-git-next-lcandy.vercel.app/bookmarklet](https://webvpn-converter-git-next-lcandy.vercel.app/bookmarklet)
