### ISSUE TITLE
使用网页无法打开

### ISSUE THREAD

**Issue by Cherish1993** [lcandy2/webvpn-converter#62]
亲爱的程序开发者：
       您好！
       我目前一直无法打开使用的网址（https://wrdvpn.vercel.app/）
       请教一下您是什么原因，如果可以的话还望您帮忙解决一下~
       非常感谢~

**Comment by lcandy2** [comment]
我这边没有任何问题。请尝试检查自己的网络连接，或尝试使用这个链接 https://wpn.citrons.cc/
