### ISSUE TITLE
webvpn-converter-main\data\db\list.txt 文件还有作用吗，我向列表中添加了自己的学校，网页中并没有显示出来

### ISSUE THREAD

**Issue by SUNYZ0525** [lcandy2/webvpn-converter#74]
山东 青岛科技大学 wvpn.qust.edu.cn
![image](https://github.com/lcandy2/webvpn-converter/assets/74035303/ff1b49b9-a448-4fc2-b0fd-d6fd1af28379)

**Comment by lcandy2** [comment]
有作用，最近在重写新的版本，很快修复

**Comment by lcandy2** [comment]
已添加
